server:
  port: 7001
eureka:
    instance: #eureka实例定义
        hostname: localhost #定义eureka实例所在主机名称
    client: #作为客户端配置
      fetch-registry: false #是否要从eureka中获取注册信息
      register-with-eureka: false #是否要注册到eureka
    server: #作为服务端配置
      eviction-interval-timer-in-ms: 1000 #设置清理间隔时间，单位：毫秒，默认60s
      enable-self-preservation: false #关闭保护模式(保护模式即掉线后，不会立即清除)