server:
  port: 8080
  servlet:
    context-path: /microcloud-provider-product #设置访问工程名
mybatis:
  mapper-locations: #mapper映射文件
    classpath:mapping/*.xml
spring:
  application:
    name: microcloud-provider-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiangxue?serverTimezone=GMT%2B8
    username: root
    password: mysql
#  security:
#    user:
#      name: admin #认证用户名
#      password: enjoy #认证密码
#      roles:
#        - USER #角色
logging:
  level:
    com.bill.mapper: debug
