server:
  port: 8080
mybatis:
  mapper-locations: #mapper映射文件
    classpath:mapping/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource;
    driver-class-name: com.mysql.cj.jdbc.Driver;
    url: jdbc:mysql://localhost:3306/xiangxue?serverTimezone=GMT%2B8
    username: root
    password: mysql
logging:
  level:
    com.bill.mapper:debug